# Site settings
title: Drink'n'Drive | Immoral racing!
description: "An 8-bit retro game for Android."
url: "http://www.drink-n-drive.org"
author:
  name: "-"
  email: "turbowaregames@gmail.com"
  url: "http://www.drink-n-drive.org"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
